#!/bin/bash
#
# bussiga reisijad
#
echo -n "Sisesta reisijate arv:"
read reisijad
echo -n "Sisesta bussi kohtade arv:"
read kohad
#
# arvutused
#
bussid=$(($reisijad / $kohad))
kohata=$(($reisijad % $kohad))
if  [ $kohata -gt 0 ]
then
	bussid=$(($bussid + 1))
fi
echo "Kokku on vaja $bussid taisbussi"
#
# skripti lõpp
