#!/bin/bash
#
# skripti algus
#
# kasutaja nime küsimine
#
echo -n "Sisesta oma ees- ja perenimi:"
read eesnimi perenimi
echo "Tere tulemast, $eesnimi $perenimi"
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi"
#
# skripti lõpp

