#!/bin/bash
#
# raami joonistamine
echo -n "Sisesta ridade arv: "
read rida
echo -n "Sisesta tärnide arv: "
read tarn
# genereerime rea numbrid
for((i = 1; i <= $rida; i++))
do
  echo -n "$i "
  # kui on esimene VÕI viimane rida
  if [ $i -eq 1 -o $i -eq $rida ]; then
  # tuleb rida tärnidest
  for((j = 1; j <= $tarn; j++))
  do
    echo -n "* "
  done
  # teised read aga
  else
    echo -n "* "
    # tühikud
    for((j = 2; j < $tarn; j++))
    do
      echo -n "  "
    done
    echo -n "* "
  fi
  echo
done
